### ISSUE TITLE
tutorial t03 runs GPU version in double and not in single

### ISSUE THREAD

**Issue by aosokin** [ASETS/asetsMatlabMaxFlow#1]
Hi,

tutorial t03_usingCUDA.m runs the computation in double precision although in comments it is said that computations are done in single precision.

One my configuration line
[u4, conv4, i4, time4] = asetsBinaryMF3D(gpuArray(Cs), gpuArray(Ct), gpuArray(alpha), pars);
takes 5 seconds.

If I call
[u4, conv4, i4, time4] = asetsBinaryMF3D(gpuArray(single(Cs)), gpuArray(single(Ct)), gpuArray(single(alpha)), pars);
it takes 1.5 seconds.

**Comment by mrajchl** [comment]
Thank you for pointing this out. Your suggestions have been changed and pushed.
